import { useState } from "react";
import { ThemeSwatch } from "./ThemeSwatch";

interface ThemePreviewProps {
  /** Theme value, e.g. "minimal-white-orange" — must match the PNG filename. */
  theme: string;
  label: string;
  className?: string;
  /** Crop to the top of the page (card use) vs. show the full scrollable page. */
  variant?: "crop" | "full";
}

/**
 * Renders the real screenshot generated by running the website-generator
 * engine against tests/website/fixtures/valid_portfolio.json for this theme
 * (see website-generator/scripts/generate_theme_previews.py). This is actual
 * generated output, not a mockup — if the image is ever missing, it falls
 * back to the abstract ThemeSwatch rather than a broken image.
 */
export function ThemePreview({ theme, label, className = "", variant = "crop" }: ThemePreviewProps) {
  const [failed, setFailed] = useState(false);
  const src = `/theme-previews/${theme}.png`;

  if (failed) {
    return <ThemeSwatch theme={theme} className={className} />;
  }

  return (
    <div className={`overflow-hidden rounded-lg border border-ink-200 bg-surface ${className}`}>
      <img
        src={src}
        alt={`${label} theme — real generated portfolio example`}
        loading="lazy"
        onError={() => setFailed(true)}
        className={
          variant === "crop"
            ? "h-full w-full object-cover object-top"
            : "h-full w-full object-cover object-top"
        }
      />
    </div>
  );
}
