"""initial schema

Revision ID: 5e2847fbfc22
Revises: 
Create Date: 2026-06-26 08:27:03.326236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2847fbfc22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTING', 'EXTRACTED', 'ANALYZING', 'ANALYZED', 'FAILED', name='resumestatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failed_stage', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('resume_schema_json', sa.JSON(), nullable=True),
    sa.Column('ai_analysis_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'DRAFT', 'PUBLISHED', 'FAILED', name='portfoliostatus'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('portfolio_schema_json', sa.JSON(), nullable=True),
    sa.Column('selected_theme', sa.Enum('MINIMAL', 'EXECUTIVE', 'DEVELOPER', 'CREATIVE', 'SAAS', name='themename'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_resume_id'), 'portfolios', ['resume_id'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_portfolio_id'), 'drafts', ['portfolio_id'], unique=False)
    op.create_table('published_sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('theme', sa.Enum('MINIMAL', 'EXECUTIVE', 'DEVELOPER', 'CREATIVE', 'SAAS', name='themename'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_sites_portfolio_id'), 'published_sites', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_published_sites_slug'), 'published_sites', ['slug'], unique=True)
    op.create_table('theme_selections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('theme', sa.Enum('MINIMAL', 'EXECUTIVE', 'DEVELOPER', 'CREATIVE', 'SAAS', name='themename'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preview_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_selections_portfolio_id'), 'theme_selections', ['portfolio_id'], unique=False)
    op.create_table('version_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('theme', sa.Enum('MINIMAL', 'EXECUTIVE', 'DEVELOPER', 'CREATIVE', 'SAAS', name='themename'), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_history_portfolio_id'), 'version_history', ['portfolio_id'], unique=False)
    op.create_table('deployment_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('published_site_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('NONE', 'NETLIFY', 'VERCEL', 'S3', name='deploymentprovider'), nullable=False),
    sa.Column('state', sa.Enum('NOT_DEPLOYED', 'QUEUED', 'DEPLOYING', 'LIVE', 'FAILED', name='deploymentstate'), nullable=False),
    sa.Column('deployed_url', sa.String(length=1024), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['published_site_id'], ['published_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_statuses_published_site_id'), 'deployment_statuses', ['published_site_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_statuses_published_site_id'), table_name='deployment_statuses')
    op.drop_table('deployment_statuses')
    op.drop_index(op.f('ix_version_history_portfolio_id'), table_name='version_history')
    op.drop_table('version_history')
    op.drop_index(op.f('ix_theme_selections_portfolio_id'), table_name='theme_selections')
    op.drop_table('theme_selections')
    op.drop_index(op.f('ix_published_sites_slug'), table_name='published_sites')
    op.drop_index(op.f('ix_published_sites_portfolio_id'), table_name='published_sites')
    op.drop_table('published_sites')
    op.drop_index(op.f('ix_drafts_portfolio_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_resume_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
