"""Pydantic v2 schema for generated portfolio content.

This schema is the contract for Milestone 4 output.
Every field has a defined type — no bare dicts or Any types are used.
The schema is generated from ResumeSchema + AIAnalysisSchema by portfolio_generator.py
and validated by portfolio_validator.py before being written to disk.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field

PORTFOLIO_SCHEMA_VERSION = "5.0"


class HeroSection(BaseModel):
    """The top-of-page hero / banner section."""

    name: str = Field(default="")
    role: str = Field(default="")
    headline: str = Field(default="")


class ContactInfo(BaseModel):
    """Contact details surfaced in the portfolio footer/contact section."""

    email: Optional[str] = None
    phone: Optional[str] = None
    location: Optional[str] = None
    linkedin: Optional[str] = None


class ProjectItem(BaseModel):
    """A single structured project entry.

    Replaces the v4.0 flat-string project description. Each field maps
    directly onto one piece of a credible project case study, so the
    website layer never has to guess a title out of free-form prose.
    """

    title: str = Field(default="")
    problem: str = Field(default="")           # what problem the project solves
    technologies: list[str] = Field(default_factory=list)
    outcome: str = Field(default="")            # result / impact statement
    github_url: Optional[str] = None            # placeholder until the user adds their repo
    demo_url: Optional[str] = None              # placeholder until the user adds a live demo


class SkillCategory(BaseModel):
    """A named group of related skills (e.g. 'Programming Languages')."""

    category: str = Field(default="")
    items: list[str] = Field(default_factory=list)


class PortfolioSchema(BaseModel):
    """Structured portfolio content ready for rendering.

    Generated by portfolio_generator.py from ResumeSchema + AIAnalysisSchema.
    Never instantiated from raw LLM output directly — always constructed via
    portfolio_generator.generate() which enforces completeness.
    """

    # ── Metadata ──────────────────────────────────────────────────────────────
    schema_version: str = Field(default=PORTFOLIO_SCHEMA_VERSION)
    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    llm_model: str = Field(default="")

    # ── Required content sections ─────────────────────────────────────────────
    hero: HeroSection
    about: str
    skills: list[SkillCategory]
    projects: list[ProjectItem]
    career_paths: list[str]
    contact: ContactInfo
